# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_notesexceptonegrid.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.NonModal)
        Window.resize(607, 264)
        Window.setAutoFillBackground(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exceptLabel = QtWidgets.QLabel(Window)
        self.exceptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exceptLabel.setObjectName("exceptLabel")
        self.gridLayout.addWidget(self.exceptLabel, 3, 1, 1, 1)
        self.velExcept = QtWidgets.QCheckBox(Window)
        self.velExcept.setText("")
        self.velExcept.setObjectName("velExcept")
        self.gridLayout.addWidget(self.velExcept, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.startTimeExcept = QtWidgets.QCheckBox(Window)
        self.startTimeExcept.setText("")
        self.startTimeExcept.setObjectName("startTimeExcept")
        self.gridLayout.addWidget(self.startTimeExcept, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.noteMin = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteMin.sizePolicy().hasHeightForWidth())
        self.noteMin.setSizePolicy(sizePolicy)
        self.noteMin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.noteMin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.noteMin.setObjectName("noteMin")
        self.gridLayout.addWidget(self.noteMin, 4, 3, 1, 1)
        self.noteMax = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteMax.sizePolicy().hasHeightForWidth())
        self.noteMax.setSizePolicy(sizePolicy)
        self.noteMax.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.noteMax.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.noteMax.setObjectName("noteMax")
        self.gridLayout.addWidget(self.noteMax, 4, 4, 1, 1)
        self.maxLabel = QtWidgets.QLabel(Window)
        self.maxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout.addWidget(self.maxLabel, 3, 4, 1, 1)
        self.noteCheckBox = QtWidgets.QCheckBox(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteCheckBox.sizePolicy().hasHeightForWidth())
        self.noteCheckBox.setSizePolicy(sizePolicy)
        self.noteCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.noteCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.noteCheckBox.setIconSize(QtCore.QSize(16, 16))
        self.noteCheckBox.setChecked(False)
        self.noteCheckBox.setObjectName("noteCheckBox")
        self.gridLayout.addWidget(self.noteCheckBox, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.minLabel = QtWidgets.QLabel(Window)
        self.minLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout.addWidget(self.minLabel, 3, 3, 1, 1)
        self.noteLabel = QtWidgets.QLabel(Window)
        self.noteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noteLabel.setObjectName("noteLabel")
        self.gridLayout.addWidget(self.noteLabel, 3, 2, 1, 1)
        self.noteNotes = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteNotes.sizePolicy().hasHeightForWidth())
        self.noteNotes.setSizePolicy(sizePolicy)
        self.noteNotes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.noteNotes.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.noteNotes.setObjectName("noteNotes")
        self.gridLayout.addWidget(self.noteNotes, 4, 2, 1, 1)
        self.endTimeCheckBox = QtWidgets.QCheckBox(Window)
        self.endTimeCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.endTimeCheckBox.setObjectName("endTimeCheckBox")
        self.gridLayout.addWidget(self.endTimeCheckBox, 7, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.startTimeCheckBox = QtWidgets.QCheckBox(Window)
        self.startTimeCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.startTimeCheckBox.setChecked(False)
        self.startTimeCheckBox.setObjectName("startTimeCheckBox")
        self.gridLayout.addWidget(self.startTimeCheckBox, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.velNotes = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velNotes.sizePolicy().hasHeightForWidth())
        self.velNotes.setSizePolicy(sizePolicy)
        self.velNotes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.velNotes.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.velNotes.setObjectName("velNotes")
        self.gridLayout.addWidget(self.velNotes, 5, 2, 1, 1)
        self.startTimeNotes = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeNotes.sizePolicy().hasHeightForWidth())
        self.startTimeNotes.setSizePolicy(sizePolicy)
        self.startTimeNotes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.startTimeNotes.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.startTimeNotes.setObjectName("startTimeNotes")
        self.gridLayout.addWidget(self.startTimeNotes, 6, 2, 1, 1)
        self.endTimeNotes = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTimeNotes.sizePolicy().hasHeightForWidth())
        self.endTimeNotes.setSizePolicy(sizePolicy)
        self.endTimeNotes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.endTimeNotes.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.endTimeNotes.setObjectName("endTimeNotes")
        self.gridLayout.addWidget(self.endTimeNotes, 7, 2, 1, 1)
        self.velCheckBox = QtWidgets.QCheckBox(Window)
        self.velCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.velCheckBox.setObjectName("velCheckBox")
        self.gridLayout.addWidget(self.velCheckBox, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.enableLabel = QtWidgets.QLabel(Window)
        self.enableLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.enableLabel.setObjectName("enableLabel")
        self.gridLayout.addWidget(self.enableLabel, 3, 0, 1, 1)
        self.endTimeMin = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTimeMin.sizePolicy().hasHeightForWidth())
        self.endTimeMin.setSizePolicy(sizePolicy)
        self.endTimeMin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.endTimeMin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.endTimeMin.setObjectName("endTimeMin")
        self.gridLayout.addWidget(self.endTimeMin, 7, 3, 1, 1)
        self.startTimeMin = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeMin.sizePolicy().hasHeightForWidth())
        self.startTimeMin.setSizePolicy(sizePolicy)
        self.startTimeMin.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.startTimeMin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.startTimeMin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.startTimeMin.setObjectName("startTimeMin")
        self.gridLayout.addWidget(self.startTimeMin, 6, 3, 1, 1)
        self.velMin = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velMin.sizePolicy().hasHeightForWidth())
        self.velMin.setSizePolicy(sizePolicy)
        self.velMin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.velMin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.velMin.setObjectName("velMin")
        self.gridLayout.addWidget(self.velMin, 5, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 5)
        self.noteExcept = QtWidgets.QCheckBox(Window)
        self.noteExcept.setText("")
        self.noteExcept.setObjectName("noteExcept")
        self.gridLayout.addWidget(self.noteExcept, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.keepFileCheckBox = QtWidgets.QCheckBox(Window)
        self.keepFileCheckBox.setObjectName("keepFileCheckBox")
        self.gridLayout.addWidget(self.keepFileCheckBox, 0, 1, 1, 1)
        self.endTimeExcept = QtWidgets.QCheckBox(Window)
        self.endTimeExcept.setText("")
        self.endTimeExcept.setObjectName("endTimeExcept")
        self.gridLayout.addWidget(self.endTimeExcept, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.run = QtWidgets.QPushButton(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run.sizePolicy().hasHeightForWidth())
        self.run.setSizePolicy(sizePolicy)
        self.run.setObjectName("run")
        self.gridLayout.addWidget(self.run, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.newFileName = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newFileName.sizePolicy().hasHeightForWidth())
        self.newFileName.setSizePolicy(sizePolicy)
        self.newFileName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.newFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileName.setClearButtonEnabled(False)
        self.newFileName.setObjectName("newFileName")
        self.gridLayout.addWidget(self.newFileName, 0, 3, 1, 1)
        self.openFile = QtWidgets.QPushButton(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFile.sizePolicy().hasHeightForWidth())
        self.openFile.setSizePolicy(sizePolicy)
        self.openFile.setAutoDefault(False)
        self.openFile.setDefault(False)
        self.openFile.setFlat(False)
        self.openFile.setObjectName("openFile")
        self.gridLayout.addWidget(self.openFile, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.fileName = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileName.sizePolicy().hasHeightForWidth())
        self.fileName.setSizePolicy(sizePolicy)
        self.fileName.setMaximumSize(QtCore.QSize(16777215, 10))
        self.fileName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fileName.setAlignment(QtCore.Qt.AlignCenter)
        self.fileName.setWordWrap(True)
        self.fileName.setObjectName("fileName")
        self.gridLayout.addWidget(self.fileName, 0, 2, 1, 1)
        self.velMax = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velMax.sizePolicy().hasHeightForWidth())
        self.velMax.setSizePolicy(sizePolicy)
        self.velMax.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.velMax.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.velMax.setObjectName("velMax")
        self.gridLayout.addWidget(self.velMax, 5, 4, 1, 1)
        self.startTimeMax = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeMax.sizePolicy().hasHeightForWidth())
        self.startTimeMax.setSizePolicy(sizePolicy)
        self.startTimeMax.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.startTimeMax.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.startTimeMax.setObjectName("startTimeMax")
        self.gridLayout.addWidget(self.startTimeMax, 6, 4, 1, 1)
        self.endTimeMax = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTimeMax.sizePolicy().hasHeightForWidth())
        self.endTimeMax.setSizePolicy(sizePolicy)
        self.endTimeMax.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.endTimeMax.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.endTimeMax.setObjectName("endTimeMax")
        self.gridLayout.addWidget(self.endTimeMax, 7, 4, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)
        Window.setTabOrder(self.openFile, self.keepFileCheckBox)
        Window.setTabOrder(self.keepFileCheckBox, self.newFileName)
        Window.setTabOrder(self.newFileName, self.run)
        Window.setTabOrder(self.run, self.noteCheckBox)
        Window.setTabOrder(self.noteCheckBox, self.noteExcept)
        Window.setTabOrder(self.noteExcept, self.noteNotes)
        Window.setTabOrder(self.noteNotes, self.noteMin)
        Window.setTabOrder(self.noteMin, self.noteMax)
        Window.setTabOrder(self.noteMax, self.velCheckBox)
        Window.setTabOrder(self.velCheckBox, self.velExcept)
        Window.setTabOrder(self.velExcept, self.velNotes)
        Window.setTabOrder(self.velNotes, self.velMin)
        Window.setTabOrder(self.velMin, self.velMax)
        Window.setTabOrder(self.velMax, self.startTimeCheckBox)
        Window.setTabOrder(self.startTimeCheckBox, self.startTimeExcept)
        Window.setTabOrder(self.startTimeExcept, self.startTimeNotes)
        Window.setTabOrder(self.startTimeNotes, self.startTimeMin)
        Window.setTabOrder(self.startTimeMin, self.startTimeMax)
        Window.setTabOrder(self.startTimeMax, self.endTimeCheckBox)
        Window.setTabOrder(self.endTimeCheckBox, self.endTimeExcept)
        Window.setTabOrder(self.endTimeExcept, self.endTimeNotes)
        Window.setTabOrder(self.endTimeNotes, self.endTimeMin)
        Window.setTabOrder(self.endTimeMin, self.endTimeMax)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Midi Transform"))
        self.exceptLabel.setText(_translate("Window", "All Notes Except"))
        self.noteMin.setText(_translate("Window", "0"))
        self.noteMax.setText(_translate("Window", "0"))
        self.maxLabel.setText(_translate("Window", "+/- Max"))
        self.noteCheckBox.setText(_translate("Window", "Note"))
        self.minLabel.setText(_translate("Window", "+/- Min"))
        self.noteLabel.setText(_translate("Window", "Note(s)"))
        self.noteNotes.setText(_translate("Window", "0"))
        self.endTimeCheckBox.setText(_translate("Window", "End Time"))
        self.startTimeCheckBox.setText(_translate("Window", "Start Time"))
        self.velNotes.setText(_translate("Window", "0"))
        self.startTimeNotes.setText(_translate("Window", "0"))
        self.endTimeNotes.setText(_translate("Window", "0"))
        self.velCheckBox.setText(_translate("Window", "Velocity"))
        self.enableLabel.setText(_translate("Window", "Enable?"))
        self.endTimeMin.setText(_translate("Window", "0"))
        self.startTimeMin.setText(_translate("Window", "0"))
        self.velMin.setText(_translate("Window", "0"))
        self.keepFileCheckBox.setText(_translate("Window", "Keep File Open"))
        self.run.setText(_translate("Window", "Run"))
        self.newFileName.setPlaceholderText(_translate("Window", "New File Name..."))
        self.openFile.setText(_translate("Window", "Open"))
        self.fileName.setText(_translate("Window", "Select File"))
        self.velMax.setText(_translate("Window", "0"))
        self.startTimeMax.setText(_translate("Window", "0"))
        self.endTimeMax.setText(_translate("Window", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

