# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_notes.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.NonModal)
        Window.resize(494, 196)
        Window.setAutoFillBackground(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFile = QtWidgets.QPushButton(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFile.sizePolicy().hasHeightForWidth())
        self.openFile.setSizePolicy(sizePolicy)
        self.openFile.setAutoDefault(False)
        self.openFile.setDefault(False)
        self.openFile.setFlat(False)
        self.openFile.setObjectName("openFile")
        self.horizontalLayout.addWidget(self.openFile, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.fileName = QtWidgets.QLabel(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileName.sizePolicy().hasHeightForWidth())
        self.fileName.setSizePolicy(sizePolicy)
        self.fileName.setMaximumSize(QtCore.QSize(16777215, 10))
        self.fileName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fileName.setAlignment(QtCore.Qt.AlignCenter)
        self.fileName.setWordWrap(True)
        self.fileName.setObjectName("fileName")
        self.horizontalLayout.addWidget(self.fileName)
        self.newFileName = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newFileName.sizePolicy().hasHeightForWidth())
        self.newFileName.setSizePolicy(sizePolicy)
        self.newFileName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.newFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileName.setClearButtonEnabled(False)
        self.newFileName.setObjectName("newFileName")
        self.horizontalLayout.addWidget(self.newFileName)
        self.run = QtWidgets.QPushButton(Window)
        self.run.setObjectName("run")
        self.horizontalLayout.addWidget(self.run, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.maxLabel = QtWidgets.QLabel(Window)
        self.maxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout.addWidget(self.maxLabel, 0, 3, 1, 1)
        self.velCheckBox = QtWidgets.QCheckBox(Window)
        self.velCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.velCheckBox.setObjectName("velCheckBox")
        self.gridLayout.addWidget(self.velCheckBox, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.noteCheckBox = QtWidgets.QCheckBox(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteCheckBox.sizePolicy().hasHeightForWidth())
        self.noteCheckBox.setSizePolicy(sizePolicy)
        self.noteCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.noteCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.noteCheckBox.setIconSize(QtCore.QSize(16, 16))
        self.noteCheckBox.setChecked(False)
        self.noteCheckBox.setObjectName("noteCheckBox")
        self.gridLayout.addWidget(self.noteCheckBox, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.enableLabel = QtWidgets.QLabel(Window)
        self.enableLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.enableLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        self.enableLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.enableLabel.setObjectName("enableLabel")
        self.gridLayout.addWidget(self.enableLabel, 0, 0, 1, 1)
        self.minLabel = QtWidgets.QLabel(Window)
        self.minLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout.addWidget(self.minLabel, 0, 2, 1, 1)
        self.noteLabel = QtWidgets.QLabel(Window)
        self.noteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noteLabel.setObjectName("noteLabel")
        self.gridLayout.addWidget(self.noteLabel, 0, 1, 1, 1)
        self.startTimeMax = QtWidgets.QSpinBox(Window)
        self.startTimeMax.setAlignment(QtCore.Qt.AlignCenter)
        self.startTimeMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startTimeMax.setMinimum(-127)
        self.startTimeMax.setMaximum(127)
        self.startTimeMax.setObjectName("startTimeMax")
        self.gridLayout.addWidget(self.startTimeMax, 3, 3, 1, 1)
        self.startTimeMin = QtWidgets.QSpinBox(Window)
        self.startTimeMin.setAlignment(QtCore.Qt.AlignCenter)
        self.startTimeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startTimeMin.setMinimum(-127)
        self.startTimeMin.setMaximum(127)
        self.startTimeMin.setObjectName("startTimeMin")
        self.gridLayout.addWidget(self.startTimeMin, 3, 2, 1, 1)
        self.velMax = QtWidgets.QSpinBox(Window)
        self.velMax.setAlignment(QtCore.Qt.AlignCenter)
        self.velMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.velMax.setMinimum(-127)
        self.velMax.setMaximum(127)
        self.velMax.setObjectName("velMax")
        self.gridLayout.addWidget(self.velMax, 2, 3, 1, 1)
        self.startTimeCheckBox = QtWidgets.QCheckBox(Window)
        self.startTimeCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.startTimeCheckBox.setChecked(False)
        self.startTimeCheckBox.setObjectName("startTimeCheckBox")
        self.gridLayout.addWidget(self.startTimeCheckBox, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.velMin = QtWidgets.QSpinBox(Window)
        self.velMin.setAlignment(QtCore.Qt.AlignCenter)
        self.velMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.velMin.setMinimum(-127)
        self.velMin.setMaximum(127)
        self.velMin.setObjectName("velMin")
        self.gridLayout.addWidget(self.velMin, 2, 2, 1, 1)
        self.noteMin = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteMin.sizePolicy().hasHeightForWidth())
        self.noteMin.setSizePolicy(sizePolicy)
        self.noteMin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.noteMin.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.noteMin.setObjectName("noteMin")
        self.gridLayout.addWidget(self.noteMin, 1, 2, 1, 1)
        self.noteMax = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteMax.sizePolicy().hasHeightForWidth())
        self.noteMax.setSizePolicy(sizePolicy)
        self.noteMax.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.noteMax.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.noteMax.setObjectName("noteMax")
        self.gridLayout.addWidget(self.noteMax, 1, 3, 1, 1)
        self.notePitchBox = QtWidgets.QLineEdit(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notePitchBox.sizePolicy().hasHeightForWidth())
        self.notePitchBox.setSizePolicy(sizePolicy)
        self.notePitchBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.notePitchBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.notePitchBox.setObjectName("notePitchBox")
        self.gridLayout.addWidget(self.notePitchBox, 1, 1, 1, 1)
        self.endTimeCheckBox = QtWidgets.QCheckBox(Window)
        self.endTimeCheckBox.setMinimumSize(QtCore.QSize(75, 0))
        self.endTimeCheckBox.setObjectName("endTimeCheckBox")
        self.gridLayout.addWidget(self.endTimeCheckBox, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.endTimeMin = QtWidgets.QSpinBox(Window)
        self.endTimeMin.setAlignment(QtCore.Qt.AlignCenter)
        self.endTimeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.endTimeMin.setMinimum(-127)
        self.endTimeMin.setMaximum(127)
        self.endTimeMin.setObjectName("endTimeMin")
        self.gridLayout.addWidget(self.endTimeMin, 4, 2, 1, 1)
        self.endTimeMax = QtWidgets.QSpinBox(Window)
        self.endTimeMax.setAlignment(QtCore.Qt.AlignCenter)
        self.endTimeMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.endTimeMax.setMinimum(-127)
        self.endTimeMax.setMaximum(127)
        self.endTimeMax.setObjectName("endTimeMax")
        self.gridLayout.addWidget(self.endTimeMax, 4, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Midi Transform"))
        self.openFile.setText(_translate("Window", "Open"))
        self.fileName.setText(_translate("Window", "Select File"))
        self.newFileName.setPlaceholderText(_translate("Window", "New File Name..."))
        self.run.setText(_translate("Window", "Run"))
        self.maxLabel.setText(_translate("Window", "+/- Max"))
        self.velCheckBox.setText(_translate("Window", "Velocity"))
        self.noteCheckBox.setText(_translate("Window", "Note"))
        self.enableLabel.setText(_translate("Window", "Enable?"))
        self.minLabel.setText(_translate("Window", "+/- Min"))
        self.noteLabel.setText(_translate("Window", "Note(s)"))
        self.startTimeCheckBox.setText(_translate("Window", "Start Time"))
        self.noteMin.setText(_translate("Window", "0"))
        self.noteMax.setText(_translate("Window", "0"))
        self.notePitchBox.setText(_translate("Window", "0"))
        self.endTimeCheckBox.setText(_translate("Window", "End Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

